# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SwiftTbSettingProject' do
  # Comment the next line if you don't want to use dynamic frameworks
   use_frameworks!
   pod 'SnapKit', '~> 5.0.1'
   pod  'KakaJSON'
  # Pods for SwiftTbSettingProject

  target 'SwiftTbSettingProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftTbSettingProjectUITests' do
    # Pods for testing
  end

end
