# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'Swift_FriendGroup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'KakaJSON'
  pod 'SnapKit', '= 5.0.1'
  pod 'Kingfisher', '5.15.6'
  pod 'YYKit'
  pod 'HandyJSON'

  # Pods for Swift_FriendGroup

  target 'Swift_FriendGroupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift_FriendGroupUITests' do
    # Pods for testing
  end

end
